### ISSUE TITLE
Quickblox issue no video and audio in call in swift 3.0

### ISSUE THREAD

**Issue by optimumbrew** [WirecardMobileServices/SuprAcceptSDK-iOS#2]
I tried to implement quickblox - video chat function into my ios app with Swift3. After test, I could call the opponent and the opponent could accept the call, but there is not video and audio show up. I confirmed the functions "receivedRemoteVideoTrack" and "receivedRemoteAudioTrack" are executed, but still no audio and video in the call. Could anyone advise? Thank you very much!

**output are attach**
![image1](https://user-images.githubusercontent.com/34236449/33867124-77258ed2-df20-11e7-9137-b0bf238b6fa5.PNG)

**Comment by WirecardMobileServices** [comment]
Hi, probably a bad post ? This has no relation to SUPR SDK :-)
